#security.oauth2.client.registration.facebook.client-id=968249886664059 
#security.oauth2.client.registration.facebook.client-secret=6de498a21ae15f3710d26a1f4be33728

security:
      oauth2:
        client:
          clientId: 968249886664059
          clientSecret: 6de498a21ae15f3710d26a1f4be33728
          accessTokenUri: https://graph.facebook.com/oauth/access_token
          userAuthorizationUri: https://www.facebook.com/dialog/oauth
          tokenName: oauth_token
          authenticationScheme: query
          clientAuthenticationScheme: form
        resource:
          userInfoUri: https://graph.facebook.com/me
    

